on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Configure CMake"
        run: echo "cmake -S . -B build -DJSON_CI=On"
      - name: "Build and test"
        run: echo "cmake --build build --target ${{ inputs.target }}"
