on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci_target:
    runs-on: ubuntu-latest
    steps:
      - name: "Test"
        run: echo "Hello, World!"
