on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci_target:
    uses: ./.github/workflows/build-and-test-ci-target.yml
      with:
        target: ci_target
